POST fcm.googleapis.com/fcm/notification 
Content-Type: application/json
Authorization: key=AAAAMWVbFvo:APA91bERkbtqZ2wS0AI6gEjXYW53_o6BPdeq2JZBt0FdQppyqB-cX9HchL4cd803aN8-K8k7sQOj33cuH8IRVypoFrHkO7vlgZ2DuU-BPpBA85bAkAeLr851fUxh9d0I2BeomiGiYlm8
project_id: 212153865978

{
   "operation": "create",
   "notification_key_name": "alan4",
   "registration_ids": ["eT5aX9nkQAKqJ7hcHBThfA:APA91bF042lQ70vD3HbAU2hldj-bL2Lt9rWTrYfaJOTnGhqXRrq7VMQh4I81K0SGpmXjIZTv72qAsN-w7JZ08P1OXpt68sgscPEWxnQ9sWgNc10jaq49CHlMvHk2FIx6V2qgaHNupF3J"]
}

###
POST fcm.googleapis.com/fcm/send
Content-Type:application/json
Authorization: key=AAAAMWVbFvo:APA91bERkbtqZ2wS0AI6gEjXYW53_o6BPdeq2JZBt0FdQppyqB-cX9HchL4cd803aN8-K8k7sQOj33cuH8IRVypoFrHkO7vlgZ2DuU-BPpBA85bAkAeLr851fUxh9d0I2BeomiGiYlm8

{
  "to": "APA91bEhfxUUK1_04CkPBIovk6FdvN5KMFL5GA0JKnLYQH0CJ_FAgbfibjmMcoAPXWmGDV-YQTUSjCFFzrB-TnEpT0UK--1txeksuC0S1con1ZVMMJHmb94",
   "data": {
      "title": "DanceFlavors",
      "body": "Get up and dance"
   },
   "android":{
      "priority":"high"
    },

}

###
POST fcm.googleapis.com/fcm/send
Content-Type:application/json
Authorization: key=AAAAMWVbFvo:APA91bERkbtqZ2wS0AI6gEjXYW53_o6BPdeq2JZBt0FdQppyqB-cX9HchL4cd803aN8-K8k7sQOj33cuH8IRVypoFrHkO7vlgZ2DuU-BPpBA85bAkAeLr851fUxh9d0I2BeomiGiYlm8

{
  "to": "APA91bFV0HYHosknMElnrGDiSj46DJnqgqSm5l_vRIWjWx8AIeqtjKE-x5GEWPrICuIWFjiYdAiJInD027UIQtHFLzTszWY3-RNGrXPrxbZdxgQKxj3Z5SU",
  "data": {
    "read": "true",
   }
}
